import './globals.scss'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TRPCLayout from './TRPCLayout'
import { BackgroundSVG } from '@/components/svg/BackgroundSVG'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <BackgroundSVG
          preserveAspectRatio='none'
          className='-z-10 absolute top-0 left-0 w-screen h-screen object-fill'
        />
        <TRPCLayout>
          <div className='w-screen h-screen p-4 flex justify-center items-center'>{children}</div>
        </TRPCLayout>
      </body>
    </html>
  )
}
