import './globals.scss'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TRPCLayout from './TRPCLayout'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { BackgroundSVG } from '@/components/svg/BackgroundSVG'
import { SessionLayout } from './SessionLayout'
import { AuthLayout } from './AuthLayout'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params: { session, locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string; session: any }
}>) {
  const messages = await getMessages()

  return (
    <html lang={locale} className='dark'>
      <body className={inter.className}>
        <SessionLayout session={session}>
          <NextIntlClientProvider messages={messages}>
            <BackgroundSVG
              preserveAspectRatio='none'
              className='-z-10 absolute top-0 left-0 w-screen h-screen object-fill'
            />

            <TRPCLayout>
              <div className='w-screen h-screen p-4 flex justify-center items-center'>
                <AuthLayout>{children}</AuthLayout>
              </div>
            </TRPCLayout>
          </NextIntlClientProvider>
        </SessionLayout>
      </body>
    </html>
  )
}
