import './globals.scss'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TRPCLayout from './TRPCLayout'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { BackgroundSVG } from '@/components/svg/BackgroundSVG'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <BackgroundSVG
            preserveAspectRatio='none'
            className='-z-10 absolute top-0 left-0 w-screen h-screen object-fill'
          />
          <TRPCLayout>
            <div className='w-screen h-screen p-4 flex justify-center items-center'>{children}</div>
          </TRPCLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
