import './globals.scss'

import type { Metadata } from 'next'
import TRPCLayout from './layout.trpc'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { BackgroundSVG } from '@/components/svg/BackgroundSVG'
import { SessionLayout } from './layout.session'
import { ClientLayout } from './layout.client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
  params: { session, locale }
}: Readonly<{
  children: React.ReactNode
  params: { locale: string; session: any }
}>) {
  const messages = await getMessages()

  return (
    <html lang={locale} className=''>
      <body>
        <SessionLayout session={session}>
          <NextIntlClientProvider messages={messages}>
            <BackgroundSVG
              preserveAspectRatio='none'
              className='-z-10 absolute top-0 left-0 w-screen h-screen object-fill'
            />
            <TRPCLayout>
              <div className='w-screen h-screen p-2 lg:p-4 flex justify-center items-center'>
                <ClientLayout>{children}</ClientLayout>
              </div>
            </TRPCLayout>
          </NextIntlClientProvider>
        </SessionLayout>
      </body>
    </html>
  )
}
